# Generated by Django 4.0.5 on 2022-07-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_ad_category_alter_ad_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='address',
        ),
    ]
