# Generated by Django 4.0.5 on 2022-07-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_ad_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
